name: "Necesse Dedicated Server"
description: "A dedicated server for the game Necesse."
version: "1.0.0"
slug: "necesse_dedicated_server"
init: false
arch:
  - aarch64
  - amd64
  - armhf
  - armv7
  - i386
startup: services
ports:
  14159/udp: 14159
options:
  slots: 10
schema:
  slots: int